// 在此处测试；当此软件包作为插件使用时，将不会编译此软件包。
function twinkle (sprite: Sprite, visTime: number, unvisTime: number, n: number) {
    fightext_skill.after(visTime, function () {
        sprite.setFlag(SpriteFlag.Invisible, true)
        fightext_skill.after(unvisTime, function () {
            sprite.setFlag(SpriteFlag.Invisible, false)
            if (n > 1) {
                twinkle(sprite, visTime, unvisTime, n - 1)
            }
        })
    })
}
fightext_character.basicSet(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, "低级死灵", function (player4) {
    fightext_character.setAtkImage(player4, fightext_character.atkimgKind.hand1, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...7..
        ......fbddddddd1df....7.
        ......ffbbddbfd1df....7.
        .......fcbbdcfddbf....7.
        .......fffbddccffff..77.
        .......ffffcfbbb1bcf777.
        ......ffffffffcd1b1f77..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................7..
        ......................7.
        ......................7.
        ......................7.
        .....................77.
        ....................777.
        ....................77..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    fightext_character.setAtkImage(player4, fightext_character.atkimgKind.hand2, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...7..
        ......fbddddddd1df....7.
        ......ffbbddbfd1df....7.
        .......fcbbdcfddbf....7.
        .......fffbddccffff..77.
        .......ffffcfbbb1bcf777.
        ......ffffffffcd1b1f77..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................7..
        ......................7.
        ......................7.
        ......................7.
        .....................77.
        ....................777.
        ....................77..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    fightext_character.setAtkImage(player4, fightext_character.atkimgKind.leg1, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...2..
        ......fbddddddd1df....2.
        ......ffbbddbfd1df....2.
        .......fcbbdcfddbf....2.
        .......fffbddccffff..22.
        .......ffffcfbbb1bcf222.
        ......ffffffffcd1b1f22..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................2..
        ......................2.
        ......................2.
        ......................2.
        .....................22.
        ....................222.
        ....................22..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    fightext_character.setAtkImage(player4, fightext_character.atkimgKind.leg2, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...2..
        ......fbddddddd1df....2.
        ......ffbbddbfd1df....2.
        .......fcbbdcfddbf....2.
        .......fffbddccffff..22.
        .......ffffcfbbb1bcf222.
        ......ffffffffcd1b1f22..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................2..
        ......................2.
        ......................2.
        ......................2.
        .....................22.
        ....................222.
        ....................22..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    fightext_character.setStImage(player4, fightext_character.stimgKind.Defence, img`
        ........................
        ........777.............
        ..........77777.........
        ..............777.......
        .........fffff..777.....
        .......ffb1111ff..77....
        ......fb1111111bf..7....
        ......f111111111f..77...
        .....ffff1111111df..7...
        ....fb111c1dd111df..7...
        ....ffb1b1fdcf11bf..77..
        .....ffbfbfb11111f...7..
        ......ffffcfdb1b1f...7..
        .......fcccfcfbfbf..77..
        ........ffffffffff..7...
        .........ffffff....77...
        .........ffffff....7....
        .....f..fffffff...77....
        .....fffffffff...77.....
        ......fffffff....7......
        ...............777......
        ............7777........
        ........................
        ........................
        `)
    fightext_character.setStImage(player4, fightext_character.stimgKind.Hitover, img`
        ........................
        ........................
        ........................
        ........................
        .................fff....
        ................fc1b....
        .........fffff..f1bf....
        .......ff1ddbcf.f11b....
        ......fb11ddbffff1bf....
        ......f111dc11dffc1bf...
        .....f11111f1bfffffff...
        .....f11111111bffffff...
        .....f1111111bfffffff...
        .....f11111f1dbfffff....
        ......f11dbc1bfffff.....
        ......fbcc1ffcfff.......
        .......ff1bfccf.........
        ........f11bf...........
        ........f1bf............
        .........c1b............
        .........fff............
        ........................
        ........................
        ........................
        `)
    fightext_character.setStImage(player4, fightext_character.stimgKind.Lie, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ...........fff..........
        .........ffffff.........
        ....fbfbffffffbfbfbf....
        ....f1b1b1ffff1b1b1f....
        ....fc111cbfbfc111cf....
        ......fffcdb1bdffff.....
        .......fb111111bf.......
        ......fcdcf11fcdcf......
        ......fbdbfddfbdbf......
        ......fddd1111dddf......
        ......fd11111111df......
        ......fd11111111df......
        .......f11111111f.......
        .......fb111111bf.......
        ........ff1111ff........
        ..........ffff..........
        `)
    fightext_character.setStImage(player4, fightext_character.stimgKind.Stand, img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `)
    fightext_character.setStImage(player4, fightext_character.stimgKind.Quickst, img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        .......ffb1111ff........
        ......fb1111111bf.......
        ......f111111111f.......
        .....ffff1111111df......
        ....fb111c1dd111df......
        ....ffb1b1fdcf11bf......
        .....ffbfbfb11111f......
        ......ffffcfdb1b1f......
        .......fcccfcfbfbf......
        ........ffffffffff......
        .........ffffff.........
        .........ffffff.........
        .....f..fffffff.........
        .....fffffffff..........
        ......fffffff...........
        ........................
        ........................
        ........................
        ........................
        `)
    fightext_character.setWalkImage(player4, fightext_character.aniKind.Hurt, [img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff11111f........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fddd111111df......
        ......fdddd11111df......
        ......fddddddd11df......
        ......fddddddd111f......
        ......fddddddcf11f......
        .......fbdddb1111bf.....
        ........fffcfdb1b1f.....
        .......ffffffffbfbf.....
        ....ff.fffffffffff......
        .....ffffffff...........
        .....ffffffb1b1f........
        ......ffffffbfbf........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........ffffff..........
        .......fb11111ff........
        ......ffd111111bf.......
        ......fdd1111111f.......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddcf11bf......
        ......fcbbb111111f......
        .......f111c1b1b1f......
        .......ff1b1ffbfbf......
        ........fbfbffffff......
        ........ffffcff.........
        .........fcccff.........
        .....f..fffffff.........
        .....fffffffff..........
        ......fffffff...........
        ........................
        ........................
        ........................
        ........................
        `])
    fightext_character.setWalkImage(player4, fightext_character.aniKind.Stand, [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `])
    fightext_character.setWalkImage(player4, fightext_character.aniKind.Walk, [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `], 100)
    player4.sprite.setFlag(SpriteFlag.Ghost, true)
    fightext_character.setAbility(player4, fightext_character.abilityKind.def, 0.4)
})
let skill: fightext_skill.skill = null
fightext_animation.defAnimation(function () {
    fightext_animation.setAnimation([img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . . . 7 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 . . . . . . . . 
        . . . . . . . . 7 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 7 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `], "抓痕", 80)
})
fightext_projectile.setProjectiles("低级死灵的弹射物集合", function () {
    fightext_projectile.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 9 1 9 . . . . . . . 
        . . . . . . 9 1 9 . . . . . . . 
        . . . . . . 7 1 9 7 . . . . . . 
        . . . . . . 7 1 9 7 . . . . . . 
        . . . . . 7 9 1 1 9 . . . . . . 
        . . . . . 7 1 1 1 9 7 . . . . . 
        . . . . . 9 1 1 1 1 7 . . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . . 7 1 1 1 1 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "鬼火", function (projectile) {
        fightext_projectile.setBullet2(projectile, fightext_projectile.bulletP2.indeflectible, true)
        fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.perishTogether,-1)
        fightext_projectile.circular(projectile, 3, 0, fightext_projectile.clockwise.p, 50)
    })
    fightext_projectile.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . 7 9 9 7 . . . . . . 
        . . . . . . 6 9 9 6 . . . . . . 
        . . . . . . . 6 6 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "死灵粒子", function (projectile) {
        fightext_projectile.setBullet2(projectile, fightext_projectile.bulletP2.breakdef, true)
        fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.damage, 5)
        projectile.ay = -100
        projectile.setFlag(SpriteFlag.AutoDestroy, false)
        fightext_projectile.then(0.5, function (projectile) {
            projectile.ay = 0
            fightext_projectile.acceToV(projectile, 0.5, 1.5, 0)
        })
        fightext_projectile.then(0.5, function (projectile) {
            fightext_projectile.circular(projectile, 30, 0)
        })
        fightext_projectile.then(2, function (projectile) {
            fightext_projectile.stopcircular(projectile)
            fightext_projectile.aimedshot(projectile)
        })
    })
    fightext_projectile.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . 7 9 9 7 . . . . . . 
        . . . . . . 6 9 9 6 . . . . . . 
        . . . . . . . 6 6 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "幽灵粒子", function (projectile) {
        fightext_projectile.setBullet2(projectile, fightext_projectile.bulletP2.breakdef, true)
        projectile.lifespan = 3000
        fightext_projectile.bulletInterval(0.5, projectile, function () {
            projectile.setFlag(SpriteFlag.Invisible, true)
        })
        fightext_skill.after(0.25, function () {
            fightext_projectile.bulletInterval(0.5, projectile, function () {
                projectile.setFlag(SpriteFlag.Invisible, false)
            })
        })
    })
    fightext_projectile.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . 7 7 7 6 . . . . . . 
        . . . . . . . 7 6 8 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "幽灵爪", function (projectile) {
        projectile.setFlag(SpriteFlag.AutoDestroy, false)
        fightext_projectile.setBullet2(projectile, fightext_projectile.bulletP2.indeflectible, true)
        projectile.lifespan = 1000
        fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.damage, 2)
        fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.hurted, 3)
        if (projectile.vy < 0) {
            fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.yspeed, 75)
        } else {
            fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.yspeed, -75)
        }
        fightext_projectile.setBullet(projectile, fightext_projectile.bulletP.perishTogether,-1)
        fightext_projectile.tailshoot(projectile, 20, "抓痕")
    })
})
fightext_skill.skillSet("低级死灵", function (player3) {
    fightext_skill.setSkill(player3, fightext_skill.SkillKind.A8, 5, function (tempVar, undefined) {
        fightext_skill.shoot2(player3, "鬼火", player3.x, player3.y)
    })
    fightext_skill.setSkill(player3, fightext_skill.SkillKind.A9, 10, function (tempVar, undefined) {
        fightext_skill.shoot2(player3, "死灵粒子", player3.x, player3.y)
    })
    fightext_skill.setSkill(player3, fightext_skill.SkillKind.A10, 15, function (tempVar, undefined) {
        fightext_skill.add2(tempVar, "projectile", fightext_skill.newPosture(player3, img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fdddddd111df...7..
            ......fbddddddd1df....7.
            ......ffbbddbfd1df....7.
            .......fcbbdcfddbf....7.
            .......fffbddccffff..77.
            .......ffffcfbbb1bcf777.
            ......ffffffffcd1b1f77..
            ...ffffffffff..fdfdf....
            .....ffffff.....f.f.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `, 0.3, img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .....................7..
            ......................7.
            ......................7.
            ......................7.
            .....................77.
            ....................777.
            ....................77..
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `))
        multishot(fightext_skill.getVal2(tempVar, "projectile"), 170, 3, 0.2, 10, "幽灵粒子")
        fightext_skill.after(0.6, function () {
            multishot(fightext_skill.getVal2(tempVar, "projectile"), 190, 3, 0.2, -10, "幽灵粒子")
        })
    })
    fightext_skill.setSkill(player3, fightext_skill.SkillKind.B9, 10, function (tempVar, undefined) {
        if (fightext_character.getSprite(player3, fightext_character.ME.M).x < fightext_character.getSprite(player3, fightext_character.ME.E).x) {
            fightext_character.getSprite(player3, fightext_character.ME.M).setPosition(fightext_character.getSprite(player3, fightext_character.ME.E).x + 10, fightext_character.getSprite(player3, fightext_character.ME.E).y)
            if (fightext_character.dirRight(player3, fightext_character.playerStatus.right)) {
                fightext_skill.turn(player3)
            }
        } else {
            fightext_character.getSprite(player3, fightext_character.ME.M).setPosition(fightext_character.getSprite(player3, fightext_character.ME.E).x - 10, fightext_character.getSprite(player3, fightext_character.ME.E).y)
            if (!(fightext_character.dirRight(player3, fightext_character.playerStatus.right))) {
                fightext_skill.turn(player3)
            }
        }
        fightext_character.atkAction(player3, fightext_character.atkKind.RushAtkA, 0.7)
        fightext_skill.immune(player3, 1)
        twinkle(fightext_character.getSprite(player3, fightext_character.ME.M), 0.2, 0.2, 5)
    })
    skill = fightext_skill.getSkill(player3, fightext_skill.SkillKind.B9)
    fightext_skill.setSkill2(player3, fightext_skill.SkillKind.B11, skill)
    fightext_skill.setSkill(player3, fightext_skill.SkillKind.A9, 5, function (tempVar, undefined) {
        fightext_skill.immune(player3, 1)
        fightext_character.atkAction(player3, fightext_character.atkKind.BasicAtkA, 0.3)
        fightext_skill.run(player3)
        fightext_skill.add3(tempVar, fightext_skill.getSkill(player3, fightext_skill.SkillKind.A), "A")
        fightext_skill.setSkill(player3, fightext_skill.SkillKind.A, 5, function (tempVar, undefined2) {
            if (fightext_character.dirRight(player3, fightext_character.playerStatus.right)) {
                fightext_skill.add(tempVar, "d", 6)
            } else {
                fightext_skill.add(tempVar, "d", -6)
            }
            fightext_character.atkAction(player3, fightext_character.atkKind.BasicAtkA)
            fightext_skill.shoot2(player3, "幽灵爪", fightext_character.getHPMPXY(player3, fightext_character.HPMP.x) + fightext_skill.getVal(tempVar, "d") * 1, fightext_character.getHPMPXY(player3, fightext_character.HPMP.y) + 10, 130, 100, -10)
            fightext_skill.shoot2(player3, "幽灵爪", fightext_character.getHPMPXY(player3, fightext_character.HPMP.x) + fightext_skill.getVal(tempVar, "d") * 2, fightext_character.getHPMPXY(player3, fightext_character.HPMP.y) + 8, 130, 105, -15)
            fightext_skill.shoot2(player3, "幽灵爪", fightext_character.getHPMPXY(player3, fightext_character.HPMP.x) + fightext_skill.getVal(tempVar, "d") * 3, fightext_character.getHPMPXY(player3, fightext_character.HPMP.y) + 6, 130, 110, -20)
            fightext_skill.setSkill(player3, fightext_skill.SkillKind.A, 5, function (tempVar, undefined3) {
                let player5: fightext_character.Character = null
                if (fightext_character.dirRight(player3, fightext_character.playerStatus.right)) {
                    fightext_skill.add(tempVar, "d", 6)
                } else {
                    fightext_skill.add(tempVar, "d", -6)
                }
                fightext_character.atkAction(player3, fightext_character.atkKind.BasicAtkA)
                fightext_skill.shoot2(player3, "幽灵爪", fightext_character.getHPMPXY(player3, fightext_character.HPMP.x) + fightext_skill.getVal(tempVar, "d") * 4, fightext_character.getHPMPXY(player3, fightext_character.HPMP.y) - 20, 230, 100, -10)
                fightext_skill.shoot2(player3, "幽灵爪", fightext_character.getHPMPXY(player3, fightext_character.HPMP.x) + fightext_skill.getVal(tempVar, "d") * 5, fightext_character.getHPMPXY(player3, fightext_character.HPMP.y) - 18, 230, 105, -15)
                fightext_skill.shoot2(player3, "幽灵爪", fightext_character.getHPMPXY(player3, fightext_character.HPMP.x) + fightext_skill.getVal(tempVar, "d") * 6, fightext_character.getHPMPXY(player3, fightext_character.HPMP.y) - 16, 230, 110, -20)
            })
        })
        fightext_skill.after(0.8, function () {
            fightext_skill.setSkill2(player3, fightext_skill.SkillKind.A, fightext_skill.getVal3(tempVar, "A"))
        })
    })
})
