// 在此处测试；当此软件包作为插件使用时，将不会编译此软件包。
function twinkle (sprite: Sprite, visTime: number, unvisTime: number, n: number) {
    myGame.after(visTime, function () {
        sprite.setFlag(SpriteFlag.Invisible, true)
        myGame.after(unvisTime, function () {
            sprite.setFlag(SpriteFlag.Invisible, false)
            if (n > 1) {
                twinkle(sprite, visTime, unvisTime, n - 1)
            }
        })
    })
}

myGame.basicSet(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, "低级死灵", function (player4) {
    myGame.setAtkImage(player4, myGame.atkimgKind.hand1, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...7..
        ......fbddddddd1df....7.
        ......ffbbddbfd1df....7.
        .......fcbbdcfddbf....7.
        .......fffbddccffff..77.
        .......ffffcfbbb1bcf777.
        ......ffffffffcd1b1f77..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................7..
        ......................7.
        ......................7.
        ......................7.
        .....................77.
        ....................777.
        ....................77..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    myGame.setAtkImage(player4, myGame.atkimgKind.hand2, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...7..
        ......fbddddddd1df....7.
        ......ffbbddbfd1df....7.
        .......fcbbdcfddbf....7.
        .......fffbddccffff..77.
        .......ffffcfbbb1bcf777.
        ......ffffffffcd1b1f77..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................7..
        ......................7.
        ......................7.
        ......................7.
        .....................77.
        ....................777.
        ....................77..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    myGame.setAtkImage(player4, myGame.atkimgKind.leg1, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...2..
        ......fbddddddd1df....2.
        ......ffbbddbfd1df....2.
        .......fcbbdcfddbf....2.
        .......fffbddccffff..22.
        .......ffffcfbbb1bcf222.
        ......ffffffffcd1b1f22..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................2..
        ......................2.
        ......................2.
        ......................2.
        .....................22.
        ....................222.
        ....................22..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    myGame.setAtkImage(player4, myGame.atkimgKind.leg2, img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df...2..
        ......fbddddddd1df....2.
        ......ffbbddbfd1df....2.
        .......fcbbdcfddbf....2.
        .......fffbddccffff..22.
        .......ffffcfbbb1bcf222.
        ......ffffffffcd1b1f22..
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .....................2..
        ......................2.
        ......................2.
        ......................2.
        .....................22.
        ....................222.
        ....................22..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    myGame.setStImage(player4, myGame.stimgKind.Defence, img`
        ........................
        ........777.............
        ..........77777.........
        ..............777.......
        .........fffff..777.....
        .......ffb1111ff..77....
        ......fb1111111bf..7....
        ......f111111111f..77...
        .....ffff1111111df..7...
        ....fb111c1dd111df..7...
        ....ffb1b1fdcf11bf..77..
        .....ffbfbfb11111f...7..
        ......ffffcfdb1b1f...7..
        .......fcccfcfbfbf..77..
        ........ffffffffff..7...
        .........ffffff....77...
        .........ffffff....7....
        .....f..fffffff...77....
        .....fffffffff...77.....
        ......fffffff....7......
        ...............777......
        ............7777........
        ........................
        ........................
        `)
    myGame.setStImage(player4, myGame.stimgKind.Hitover, img`
        ........................
        ........................
        ........................
        ........................
        .................fff....
        ................fc1b....
        .........fffff..f1bf....
        .......ff1ddbcf.f11b....
        ......fb11ddbffff1bf....
        ......f111dc11dffc1bf...
        .....f11111f1bfffffff...
        .....f11111111bffffff...
        .....f1111111bfffffff...
        .....f11111f1dbfffff....
        ......f11dbc1bfffff.....
        ......fbcc1ffcfff.......
        .......ff1bfccf.........
        ........f11bf...........
        ........f1bf............
        .........c1b............
        .........fff............
        ........................
        ........................
        ........................
        `)
    myGame.setStImage(player4, myGame.stimgKind.Lie, img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ...........fff..........
        .........ffffff.........
        ....fbfbffffffbfbfbf....
        ....f1b1b1ffff1b1b1f....
        ....fc111cbfbfc111cf....
        ......fffcdb1bdffff.....
        .......fb111111bf.......
        ......fcdcf11fcdcf......
        ......fbdbfddfbdbf......
        ......fddd1111dddf......
        ......fd11111111df......
        ......fd11111111df......
        .......f11111111f.......
        .......fb111111bf.......
        ........ff1111ff........
        ..........ffff..........
        `)
    myGame.setStImage(player4, myGame.stimgKind.Stand, img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `)
    myGame.setStImage(player4, myGame.stimgKind.Quickst, img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        .......ffb1111ff........
        ......fb1111111bf.......
        ......f111111111f.......
        .....ffff1111111df......
        ....fb111c1dd111df......
        ....ffb1b1fdcf11bf......
        .....ffbfbfb11111f......
        ......ffffcfdb1b1f......
        .......fcccfcfbfbf......
        ........ffffffffff......
        .........ffffff.........
        .........ffffff.........
        .....f..fffffff.........
        .....fffffffff..........
        ......fffffff...........
        ........................
        ........................
        ........................
        ........................
        `)
    myGame.setWalkImage(player4, myGame.aniKind.Hurt, [img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff11111f........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fddd111111df......
        ......fdddd11111df......
        ......fddddddd11df......
        ......fddddddd111f......
        ......fddddddcf11f......
        .......fbdddb1111bf.....
        ........fffcfdb1b1f.....
        .......ffffffffbfbf.....
        ....ff.fffffffffff......
        .....ffffffff...........
        .....ffffffb1b1f........
        ......ffffffbfbf........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........ffffff..........
        .......fb11111ff........
        ......ffd111111bf.......
        ......fdd1111111f.......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddcf11bf......
        ......fcbbb111111f......
        .......f111c1b1b1f......
        .......ff1b1ffbfbf......
        ........fbfbffffff......
        ........ffffcff.........
        .........fcccff.........
        .....f..fffffff.........
        .....fffffffff..........
        ......fffffff...........
        ........................
        ........................
        ........................
        ........................
        `])
    myGame.setWalkImage(player4, myGame.aniKind.Stand, [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `])
    myGame.setWalkImage(player4, myGame.aniKind.Walk, [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `], 100)
    player4.sprite.setFlag(SpriteFlag.Ghost, true)
    myGame.setAbility(player4, myGame.abilityKind.def, 0.4)
})
myGame.setProjectiles("低级死灵的弹射物集合", function () {
    myGame.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 9 1 9 . . . . . . . 
        . . . . . . 9 1 9 . . . . . . . 
        . . . . . . 7 1 9 7 . . . . . . 
        . . . . . . 7 1 9 7 . . . . . . 
        . . . . . 7 9 1 1 9 . . . . . . 
        . . . . . 7 1 1 1 9 7 . . . . . 
        . . . . . 9 1 1 1 1 7 . . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . 7 1 1 1 1 1 1 7 . . . . 
        . . . . . 7 1 1 1 1 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "鬼火", function (projectile) {
        myGame.setBullet2(projectile, myGame.bulletP2.indeflectible, true)
        myGame.setBullet(projectile, myGame.bulletP.perishTogether, -1)
        myGame.circular(projectile, 3, 0, myGame.clockwise.p, 50)
    })
    myGame.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . 7 9 9 7 . . . . . . 
        . . . . . . 6 9 9 6 . . . . . . 
        . . . . . . . 6 6 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "死灵粒子", function (projectile) {
        myGame.setBullet2(projectile, myGame.bulletP2.breakdef, true)
        myGame.setBullet(projectile, myGame.bulletP.damage, 5)
        projectile.ay = -100
        projectile.setFlag(SpriteFlag.AutoDestroy, false)
        myGame.then(0.5, function (projectile) {
            projectile.ay = 0
            myGame.acceToV(projectile, 0.5, 1.5, 0)
        })
        myGame.then(0.5, function (projectile) {
            myGame.circular(projectile, 30, 0)
        })
        myGame.then(2, function (projectile) {
            myGame.stopcircular(projectile)
            myGame.aimedshot(projectile)
        })
    })
    myGame.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . 7 9 9 7 . . . . . . 
        . . . . . . 6 9 9 6 . . . . . . 
        . . . . . . . 6 6 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "幽灵粒子", function (projectile) {
        myGame.setBullet2(projectile, myGame.bulletP2.breakdef, true)
        projectile.lifespan = 3000
        myGame.bulletInterval(0.5, projectile, function () {
            projectile.setFlag(SpriteFlag.Invisible, true)
        })
        myGame.after(0.25, function () {
            myGame.bulletInterval(0.5, projectile, function () {
                projectile.setFlag(SpriteFlag.Invisible, false)
            })
        })
    })
    myGame.setProjectile(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 7 . . . . . . . 
        . . . . . . 7 7 7 6 . . . . . . 
        . . . . . . . 7 6 8 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, "幽灵爪", function (projectile) {
        projectile.setFlag(SpriteFlag.AutoDestroy, false)
        myGame.setBullet2(projectile, myGame.bulletP2.indeflectible, true)
        projectile.lifespan = 1000
        myGame.setBullet(projectile, myGame.bulletP.damage, 2)
        myGame.setBullet(projectile, myGame.bulletP.hurted, 3)
        if (projectile.vy < 0) {
            myGame.setBullet(projectile, myGame.bulletP.yspeed, 75)
        } else {
            myGame.setBullet(projectile, myGame.bulletP.yspeed, -75)
        }
        myGame.setBullet(projectile, myGame.bulletP.perishTogether, -1)
        myGame.tailshoot(projectile, 20, "抓痕")
    })
})
let skill: myGame.skill = null
myGame.skillSet("低级死灵", function (player3) {
    myGame.setSkill(player3, myGame.SkillKind.A8, 5, function (tempVar, player2) {
        myGame.shoot2(player2, "鬼火", player2.x, player2.y)
    })
    myGame.setSkill(player3, myGame.SkillKind.A9, 10, function (tempVar, player3) {
        myGame.shoot2(player3, "死灵粒子", player3.x, player3.y)
    })
    myGame.setSkill(player3, myGame.SkillKind.A10, 15, function (tempVar, player3) {
        myGame.add2(tempVar, "projectile", myGame.newPosture(player3, img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fdddddd111df...7..
            ......fbddddddd1df....7.
            ......ffbbddbfd1df....7.
            .......fcbbdcfddbf....7.
            .......fffbddccffff..77.
            .......ffffcfbbb1bcf777.
            ......ffffffffcd1b1f77..
            ...ffffffffff..fdfdf....
            .....ffffff.....f.f.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `, 0.3, img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .....................7..
            ......................7.
            ......................7.
            ......................7.
            .....................77.
            ....................777.
            ....................77..
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `))
        multishot(myGame.getVal2(tempVar, "projectile"), 170, 3, 0.2, 10, "幽灵粒子")
        myGame.after(0.6, function () {
            multishot(myGame.getVal2(tempVar, "projectile"), 190, 3, 0.2, -10, "幽灵粒子")
        })
    })
    myGame.setSkill(player3, myGame.SkillKind.B9, 10, function (tempVar, player2) {
        if (myGame.getSprite(player2, myGame.ME.M).x < myGame.getSprite(player2, myGame.ME.E).x) {
            myGame.getSprite(player2, myGame.ME.M).setPosition(myGame.getSprite(player2, myGame.ME.E).x + 10, myGame.getSprite(player2, myGame.ME.E).y)
            if (myGame.dirRight(player2, myGame.playerStatus.right)) {
                myGame.turn(player2)
            }
        } else {
            myGame.getSprite(player2, myGame.ME.M).setPosition(myGame.getSprite(player2, myGame.ME.E).x - 10, myGame.getSprite(player2, myGame.ME.E).y)
            if (!(myGame.dirRight(player2, myGame.playerStatus.right))) {
                myGame.turn(player2)
            }
        }
        myGame.atkAction(player2, myGame.atkKind.RushAtkA, 0.7)
        myGame.immune(player2, 1)
        twinkle(myGame.getSprite(player2, myGame.ME.M), 0.2, 0.2, 5)
    })
    skill = myGame.getSkill(player3, myGame.SkillKind.B9)
    myGame.setSkill2(player3, myGame.SkillKind.B11, skill)
    myGame.setSkill(player3, myGame.SkillKind.A9, 5, function (tempVar, player2) {
        myGame.immune(player2, 1)
        myGame.atkAction(player2, myGame.atkKind.BasicAtkA, 0.3)
        myGame.run(player2)
        myGame.add3(tempVar, myGame.getSkill(player3, myGame.SkillKind.A), "A")
        myGame.setSkill(player3, myGame.SkillKind.A, 5, function (tempVar, player4) {
            if (myGame.dirRight(player4, myGame.playerStatus.right)) {
                myGame.add(tempVar, "d", 6)
            } else {
                myGame.add(tempVar, "d", -6)
            }
            myGame.atkAction(player4, myGame.atkKind.BasicAtkA)
            myGame.shoot2(player4, "幽灵爪", myGame.getHPMPXY(player4, myGame.HPMP.x) + myGame.getVal(tempVar, "d") * 1, myGame.getHPMPXY(player4, myGame.HPMP.y) + 10, 130, 100, -10)
            myGame.shoot2(player4, "幽灵爪", myGame.getHPMPXY(player4, myGame.HPMP.x) + myGame.getVal(tempVar, "d") * 2, myGame.getHPMPXY(player4, myGame.HPMP.y) + 8, 130, 105, -15)
            myGame.shoot2(player4, "幽灵爪", myGame.getHPMPXY(player4, myGame.HPMP.x) + myGame.getVal(tempVar, "d") * 3, myGame.getHPMPXY(player4, myGame.HPMP.y) + 6, 130, 110, -20)
            myGame.setSkill(player3, myGame.SkillKind.A, 5, function (tempVar, player5) {
                if (myGame.dirRight(player5, myGame.playerStatus.right)) {
                    myGame.add(tempVar, "d", 6)
                } else {
                    myGame.add(tempVar, "d", -6)
                }
                myGame.atkAction(player5, myGame.atkKind.BasicAtkA)
                myGame.shoot2(player5, "幽灵爪", myGame.getHPMPXY(player5, myGame.HPMP.x) + myGame.getVal(tempVar, "d") * 4, myGame.getHPMPXY(player5, myGame.HPMP.y) - 20, 230, 100, -10)
                myGame.shoot2(player5, "幽灵爪", myGame.getHPMPXY(player5, myGame.HPMP.x) + myGame.getVal(tempVar, "d") * 5, myGame.getHPMPXY(player5, myGame.HPMP.y) - 18, 230, 105, -15)
                myGame.shoot2(player5, "幽灵爪", myGame.getHPMPXY(player5, myGame.HPMP.x) + myGame.getVal(tempVar, "d") * 6, myGame.getHPMPXY(player5, myGame.HPMP.y) - 16, 230, 110, -20)
            })
        })
        myGame.after(0.8, function () {
            myGame.setSkill2(player3, myGame.SkillKind.A, myGame.getVal3(tempVar, "A"))
        })
    })
})
